# Generated by Django 4.0.3 on 2022-05-31 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('value', models.CharField(max_length=20)),
                ('content', models.CharField(blank=True, max_length=255)),
                ('cover', models.CharField(blank=True, max_length=255)),
                ('classi', models.CharField(blank=True, max_length=20)),
            ],
        ),
    ]
