# Generated by Django 4.0.3 on 2022-06-06 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chaapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtotal', models.IntegerField(default=0)),
                ('shipping', models.IntegerField(default=0)),
                ('grandtotal', models.IntegerField(default=0)),
                ('customname', models.CharField(default='', max_length=100)),
                ('customemail', models.CharField(default='', max_length=100)),
                ('customaddress', models.CharField(default='', max_length=100)),
                ('customphone', models.CharField(default='', max_length=100)),
                ('paytype', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.RenameField(
            model_name='book',
            old_name='classi',
            new_name='Classify',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='content',
            new_name='Content',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='cover',
            new_name='Cover',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='name',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='value',
            new_name='Price',
        ),
        migrations.CreateModel(
            name='detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(default='', max_length=100)),
                ('unitprice', models.IntegerField(default=0)),
                ('quantity', models.IntegerField(default=0)),
                ('dtotal', models.IntegerField(default=0)),
                ('dorder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chaapp.order')),
            ],
        ),
    ]
